AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Serverless S3 Uploader - upload files to S3 buckets from your web applications
  using pre-signed URLs.

  '
Globals:
  Api:
    EndpointConfiguration: EDGE
    Cors:
      AllowMethods: '''OPTIONS,GET'''
      AllowHeaders: '''Content-Type'''
      AllowOrigin: '''*'''
  Function:
    Timeout: 5
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - '*'
          AllowedMethods:
          - GET
          - PUT
          - POST
          - DELETE
          - HEAD
          AllowedOrigins:
          - '*'
  S3UploaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://cloud-computing-03121995/Lambda/s3UploaderFunction.zip
      Handler: app.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Environment:
        Variables:
          UploadBucket:
            Ref: S3Bucket
      Policies:
      - S3CrudPolicy:
          BucketName:
            Ref: S3Bucket
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: /
            Method: get
Outputs:
  S3UploaderFunction:
    Description: Lambda Function ARN
    Value:
      Fn::GetAtt:
      - S3UploaderFunction
      - Arn
  S3UploaderFunctionIamRole:
    Description: Implicit IAM Role created for function
    Value:
      Fn::GetAtt:
      - S3UploaderFunctionRole
      - Arn
  S3BucketName:
    Description: S3 bucket
    Value:
      Ref: S3Bucket
